## Lookup up a player's career stats

If you specify the `lookupyear` value, the lookup will be fast.

In [1]:
import mlbstats
tg = mlbstats.get_player_data("Tony Gwynn", lookupyear=1982)
tg

,season,G,AO,R,2B,3B,HR,SO,BB,IBB,...,TB,RBI,SH,SF,BABIP,GO_AO,AB_HR,GO,LOB,numberOfPitches
0,1982,54,0,33,12,2,1,16,14,0,...,74,17,4,1,.310,-.--,190.00,NaN,NaN,NaN
1,1983,86,0,34,12,2,1,21,23,5,...,113,37,4,3,.326,-.--,304.00,NaN,NaN,NaN
2,1984,158,0,88,21,10,5,23,59,13,...,269,71,6,2,.359,-.--,121.20,NaN,NaN,NaN
3,1985,154,0,90,29,5,6,33,45,4,...,254,46,1,1,.327,-.--,103.67,NaN,NaN,NaN
4,1986,160,0,107,33,7,14,35,52,11,...,300,59,2,2,.331,-.--,45.86,NaN,NaN,NaN
5,1987,157,0,119,36,13,7,35,82,26,...,301,54,2,4,.383,-.--,84.14,NaN,NaN,NaN
6,1988,133,0,64,22,5,7,40,51,13,...,216,70,4,2,.328,-.--,74.43,NaN,NaN,NaN
7,1989,158,0,82,27,7,4,30,56,16,...,256,62,11,7,.345,-.--,151.00,NaN,NaN,NaN
8,1990,141,0,79,29,10,4,23,44,20,...,238,72,7,4,.315,-.--,143.25,NaN,NaN,NaN
9,1991,134,0,69,27,11,4,19,34,8,...,229,62,0,5,.320,-.--,132.50,NaN,NaN,NaN
10,1992,128,0,77,27,3,6,16,46,12,...,216,41,0,3,.317,-.--,86.67,NaN,NaN,NaN
11,1993,122,0,70,41,3,7,19,36,11,...,243,59,1,7,.357,-.--,69.86,NaN,NaN,NaN
12,1994,110,0,79,35,1,12,19,48,16,...,238,64,1,5,.389,-.--,34.92,NaN,NaN,NaN
13,1995,135,0,82,33,1,9,15,35,10,...,259,90,0,6,.364,-.--,59.44,NaN,NaN,NaN
14,1996,116,0,67,27,2,3,17,39,12,...,199,50,1,6,.357,-.--,150.33,NaN,NaN,NaN
15,1997,149,0,97,49,2,17,28,43,12,...,324,119,1,12,.363,-.--,34.82,NaN,NaN,NaN
16,1998,127,0,65,35,0,16,18,35,6,...,231,69,0,8,.303,-.--,28.81,NaN,NaN,NaN
17,1999,111,133,59,27,0,10,14,29,5,...,196,62,0,4,.330,0.97,41.10,129.0,140.0,NaN
18,2000,36,51,17,12,0,1,4,9,2,...,56,17,0,3,.320,0.67,127.00,34.0,62.0,NaN
19,2001,71,28,5,9,1,1,9,10,1,...,47,17,0,0,.348,1.14,102.00,32.0,53.0,424.0

## Automatic year search
If you don't specify a value for `lookupyear`, the call will walk back from 2020, one year at a time, until it finds a match. This could produce unexpected results, as with Tony Gwynn Jr.

In [2]:
tg2 = mlbstats.get_player_data("Tony Gwynn")
tg2

,season,G,GO,AO,R,2B,3B,HR,SO,BB,...,numberOfPitches,PA,TB,RBI,LOB,SH,SF,BABIP,GO_AO,AB_HR
0,2006,32,25,18,5,2,1,0,15,2,...,276,80,24,4,22,0,1,.317,1.39,-.--
1,2007,69,39,28,13,3,2,0,24,12,...,563,135,39,10,42,0,0,.323,1.39,-.--
2,2008,29,14,16,5,1,0,0,7,4,...,175,49,9,1,27,1,1,.222,0.88,-.--
3,2009,119,128,104,59,11,6,2,65,48,...,1811,451,135,21,104,5,3,.316,1.23,196.50
4,2010,117,110,81,30,9,3,3,50,41,...,1344,339,83,20,112,7,1,.236,1.36,96.33
5,2011,136,111,66,37,12,6,2,61,23,...,1291,340,110,22,114,2,2,.311,1.68,156.00
6,2012,103,95,60,29,8,4,0,52,16,...,1042,277,76,17,98,2,0,.290,1.58,-.--
7,2014,80,40,32,14,2,1,0,23,15,...,486,127,20,3,21,6,0,.195,1.25,-.--

The further back the player is, the longer it will take, so it's best to just specify a lookup year (any year in the player's career).

In [3]:
mm = mlbstats.get_player_data("Mickey Mantle", lookupyear=1952)
wb = mlbstats.get_player_data("Wade Boggs", lookupyear=1994)
hw = mlbstats.get_player_data("Honus Wagner", lookupyear=1910)
oz = mlbstats.get_player_data("Ozzie Smith", lookupyear=1994)

Some of the floating point fields do not automatically convert to floats, so you need to do that explicitly when you're working w/the data.

In [5]:
hw.dtypes

season     object
G           int64
AO          int64
R           int64
2B          int64
3B          int64
HR          int64
BB          int64
H           int64
HBP         int64
AVG        object
AB          int64
OBP        object
SLG        object
OPS        object
SB          int64
PA          int64
TB          int64
RBI         int64
SH          int64
BABIP      object
GO_AO      object
AB_HR      object
SO        float64
CS        float64
SBP        object
dtype: object

In [6]:
hw['AVG'].astype('float').mean()

0.32738095238095233

In [7]:
[x['AVG'].astype('float').mean() for x in [tg, mm, wb, hw, oz]]

[0.33540000000000003,
 0.2967222222222222,
 0.3257777777777778,
 0.32738095238095233,
 0.2597894736842105]

In [8]:
[x['SB'].mean() for x in [tg, mm, wb, hw, oz]]

[15.95, 8.5, 1.3333333333333333, 34.38095238095238, 30.526315789473685]

In [9]:
[x['HR'].mean() for x in [tg, mm, wb, hw, oz]]

[6.75,
 29.77777777777778,
 6.555555555555555,
 4.809523809523809,
 1.4736842105263157]